100% 968/968 [03:52<00:00,  4.17it/s]
100% 968/968 [03:53<00:00,  4.15it/s]
100% 968/968 [03:54<00:00,  4.12it/s]
100% 968/968 [03:57<00:00,  4.07it/s]
100% 968/968 [03:54<00:00,  4.12it/s]
100% 968/968 [03:53<00:00,  4.15it/s]
100% 968/968 [03:54<00:00,  4.14it/s]
100% 968/968 [03:54<00:00,  4.14it/s]
100% 968/968 [03:52<00:00,  4.17it/s]
100% 968/968 [03:55<00:00,  4.11it/s]
100% 968/968 [03:53<00:00,  4.15it/s]
100% 968/968 [03:54<00:00,  4.13it/s]
100% 968/968 [03:55<00:00,  4.11it/s]
100% 968/968 [03:55<00:00,  4.10it/s]
100% 968/968 [03:56<00:00,  4.09it/s]
100% 968/968 [04:29<00:00,  3.60it/s]
100% 968/968 [03:55<00:00,  4.11it/s]
100% 968/968 [03:56<00:00,  4.10it/s]
100% 968/968 [03:57<00:00,  4.08it/s]
100% 968/968 [03:57<00:00,  4.07it/s]
100% 968/968 [03:58<00:00,  4.05it/s]
100% 968/968 [03:58<00:00,  4.07it/s]
100% 968/968 [03:57<00:00,  4.08it/s]
100% 968/968 [03:43<00:00,  4.34it/s]
100% 968/968 [03:46<00:00,  4.28it/s]
100% 968/968 [03:45<00:00,  4.29it/s]
100% 968/968 [03:44<00:00,  4.32it/s]
100% 968/968 [03:42<00:00,  4.35it/s]
100% 968/968 [03:44<00:00,  4.31it/s]
100% 968/968 [03:47<00:00,  4.25it/s]
100% 968/968 [03:49<00:00,  4.21it/s]
100% 968/968 [03:47<00:00,  4.25it/s]
100% 968/968 [03:44<00:00,  4.31it/s]
100% 968/968 [03:44<00:00,  4.32it/s]
100% 968/968 [03:42<00:00,  4.34it/s]
100% 968/968 [03:41<00:00,  4.38it/s]
100% 968/968 [03:45<00:00,  4.30it/s]
100% 968/968 [03:46<00:00,  4.28it/s]
100% 968/968 [03:45<00:00,  4.28it/s]
100% 968/968 [03:44<00:00,  4.31it/s]
100% 968/968 [03:49<00:00,  4.22it/s]
100% 968/968 [03:52<00:00,  4.17it/s]
100% 968/968 [03:50<00:00,  4.20it/s]
100% 968/968 [03:44<00:00,  4.31it/s]
100% 968/968 [03:44<00:00,  4.32it/s]
100% 968/968 [03:45<00:00,  4.30it/s]
100% 968/968 [03:43<00:00,  4.33it/s]
100% 968/968 [03:41<00:00,  4.37it/s]
100% 968/968 [03:47<00:00,  4.25it/s]
100% 968/968 [03:53<00:00,  4.14it/s]
100% 968/968 [03:38<00:00,  4.43it/s]
100% 968/968 [03:51<00:00,  4.19it/s]
100% 968/968 [03:42<00:00,  4.35it/s]
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2024-11-15 14:37:10,262 INFO 44 [run_train_sin.py:61] Rank=0, caught unexpected error: Traceback (most recent call last):
  File "/nfs_beijing_ai/jinxian/rama-scoring1.3.0/bin/sin_equiformerV2_train_shs/../..//run_train_sin.py", line 55, in main
    test_run_train(args, yaml_args["config_runtime"], yaml_args["config_model"], yaml_args["config_data"])
  File "/nfs_beijing_ai/jinxian/rama-scoring1.3.0/utils/../dataset/sin_equiformerv2_dataset.py", line 1463, in test_run_train
    predicted_tran=predicted_atom_trans,
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in log
    self._log(data=data, step=step, commit=commit)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1334, in _log
    self._partial_history_callback(data, step, commit)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1223, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 62, in _publish_partial_history
    self._publish(rec)
  File "/nfs_beijing/kubeflow-user/jinxian_2024/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown